#ifndef ENGINE_EVENT_H
#define ENGINE_EVENT_H

#include <inttypes.h>
#include <utility/math.h>

typedef enum EventType
{
    EVENT_TYPE_NONE = 0,
    EVENT_TYPE_PRESS,
    EVENT_TYPE_RELEASE,
    EVENT_TYPE_REPEAT,
    EVENT_TYPE_MOVE,
} EventType;

typedef enum MouseButton
{
    MOUSE_BUTTON_NONE = 0,

    MOUSE_BUTTON_1,  // Left
    MOUSE_BUTTON_2,  // Right
    MOUSE_BUTTON_3,  // Middle
    MOUSE_BUTTON_4,
    MOUSE_BUTTON_5,
    MOUSE_BUTTON_6,
    MOUSE_BUTTON_7,
    MOUSE_BUTTON_8,
} MouseButton;

typedef enum KeyboardKey
{
    KEYBORAD_KEY_NONE = 0,

    KEYBORAD_KEY_A,
    KEYBORAD_KEY_B,
    KEYBORAD_KEY_C,
    KEYBORAD_KEY_D,
    KEYBORAD_KEY_E,
    KEYBORAD_KEY_F,
    KEYBORAD_KEY_G,
    KEYBORAD_KEY_H,
    KEYBORAD_KEY_I,
    KEYBORAD_KEY_J,
    KEYBORAD_KEY_K,
    KEYBORAD_KEY_L,
    KEYBORAD_KEY_M,
    KEYBORAD_KEY_N,
    KEYBORAD_KEY_O,
    KEYBORAD_KEY_P,
    KEYBORAD_KEY_Q,
    KEYBORAD_KEY_R,
    KEYBORAD_KEY_S,
    KEYBORAD_KEY_T,
    KEYBORAD_KEY_U,
    KEYBORAD_KEY_V,
    KEYBORAD_KEY_W,
    KEYBORAD_KEY_X,
    KEYBORAD_KEY_Y,
    KEYBORAD_KEY_Z,

    KEYBORAD_KEY_SPACE,
    KEYBORAD_KEY_SHIFT,
    KEYBORAD_KEY_CAPS,
    KEYBORAD_KEY_TAB,
    KEYBORAD_KEY_CONTROL,
    KEYBORAD_KEY_ESCAPE,
    KEYBORAD_KEY_ENTER,
    KEYBORAD_KEY_BACKSPACE,
    KEYBORAD_KEY_DELETE,

    KEYBORAD_KEY_RIGHT_ARROW,
    KEYBORAD_KEY_LEFT_ARROW,
    KEYBORAD_KEY_UP_ARROW,
    KEYBORAD_KEY_DOWN_ARROW,

    KEYBORAD_KEY_0,
    KEYBORAD_KEY_1,
    KEYBORAD_KEY_2,
    KEYBORAD_KEY_3,
    KEYBORAD_KEY_4,
    KEYBORAD_KEY_5,
    KEYBORAD_KEY_6,
    KEYBORAD_KEY_7,
    KEYBORAD_KEY_8,
    KEYBORAD_KEY_9,
    KEYBORAD_KEY_MINUS,
    KEYBORAD_KEY_PLUS,
    KEYBORAD_KEY_BRACKET_OPEN,
    KEYBORAD_KEY_BRACKET_CLOSE,
    KEYBORAD_KEY_VETICAL_LINE,
    KEYBORAD_KEY_COLON,
    KEYBORAD_KEY_APOSTROPHIE,
    KEYBORAD_KEY_COMMA,
    KEYBORAD_KEY_PERIOD,
    KEYBORAD_KEY_SLASH,

    KEYBORAD_KEY_F1,
    KEYBORAD_KEY_F2,
    KEYBORAD_KEY_F3,
    KEYBORAD_KEY_F4,
    KEYBORAD_KEY_F5,
    KEYBORAD_KEY_F6,
    KEYBORAD_KEY_F7,
    KEYBORAD_KEY_F8,
    KEYBORAD_KEY_F9,
    KEYBORAD_KEY_F10,
    KEYBORAD_KEY_F11,
    KEYBORAD_KEY_F12,
} KeyboardKey;

typedef struct Event
{
    union
    {
        KeyboardKey keyboard_key;
        MouseButton mouse_button;
    };
    EventType type;
} Event;

typedef void (*EventHandler)(const Event e);

#endif